import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Button from "@mui/material/Button";
import SendIcon from "@mui/icons-material/Send";
import Background from "../components/Background";
import { useUser, getSession } from "@auth0/nextjs-auth0";
import Layout from "../components/Layout";
import Header from "../components/header";
import Card from "@mui/material/Card";
import CardContent from "@mui/material/CardContent";
import CardMedia from "@mui/material/CardMedia";
import Typography from "@mui/material/Typography";
import { CardActionArea } from "@mui/material";

const Home: NextPage = () => {
  const { user } = useUser();
  // const session = getSession();
  // console.log(user);

  return (
    <>
      <Header />

      <Layout title="Landing Page" description="Landing Page">
        <div>
          <Head>
            <title>Donefirst.</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <main className="min-h-screen font-raleway">
            <div className="mb-10">
              <h1 className="mt-4 text-teal-400 flex justify-center mb-10 flex items-end ">
                <span className="mb-2">Welcome to </span>
                <span className="font-sanspro ml-2 text-6xl"> {" Done."}</span>
              </h1>

              <div className=" flex flex-row justify-center gap-10 ">
                <Card sx={{ maxWidth: 345 }}>
                  <CardActionArea>
                    <CardMedia
                      component="img"
                      height="140"
                      image="/bicycle.jpg"
                      alt="green iguana"
                    />
                    <CardContent>
                      <Typography gutterBottom variant="h5" component="div">
                        We Care.
                      </Typography>
                      <Typography variant="body2" color="text.secondary">
                        Done is a mental health platform that is designed to
                        help patients and provide the best experience!
                      </Typography>
                    </CardContent>
                  </CardActionArea>
                </Card>

                <div className="text-black w-1/3">
                  Lorem ipsum dolor sit, amet consectetur adipisicing elit. Non
                  nesciunt nam rerum. Libero quae molestiae ullam at veniam
                  atque eum doloremque deleniti eveniet. Maiores harum cum
                  officia doloribus dicta culpa?
                  <div className="flex gap-10 justify-center flex-col items-center mt-10 mr-6 ">
                    <Link href="/home">
                      <Button color="primary" size="medium" variant="outlined">
                        Book your Appointment Today!
                      </Button>
                    </Link>
                  </div>
                </div>
              </div>

              <div className="text-black  justify-center gap-10 flex mt-4">
                <div className="text-black w-1/3 mt-10">
                  Lorem ipsum dolor sit, amet consectetur adipisicing elit. Non
                  nesciunt nam rerum. Libero quae molestiae ullam at veniam
                  atque eum doloremque deleniti eveniet. Maiores harum cum
                  officia doloribus dicta culpa?
                </div>
                <Card sx={{ maxWidth: 345 }}>
                  <CardActionArea>
                    <CardMedia
                      component="img"
                      height="140"
                      image="/spain-mountains.jpg"
                      alt="green iguana"
                    />
                    <CardContent>
                      <Typography gutterBottom variant="h5" component="div">
                        Helping Patients
                      </Typography>
                      <Typography variant="body2" color="text.secondary">
                        We are commited to connecting patients throughout the
                        United States connecting with providers and receiving
                        assistance of the highest quality.
                      </Typography>
                    </CardContent>
                  </CardActionArea>
                </Card>
              </div>
            </div>

            <></>
          </main>

          <footer>
            <div className=" inset-x-0 bottom-0 text-gray-400 flex justify-center">
              Personal Project by Chinmay B - intended purely for academic
              audiences.
            </div>
          </footer>
        </div>
        <Background />
      </Layout>
    </>
  );
};

export default Home;
